### PR TITLE
[FIX] omssa macOS

### PR DESCRIPTION
**Pull request by oliveralka**
Omssa for MacOS 10.15

@jpfeuffer I am not sure why this other commit is there (percolator - could you have a look if that is ok?)

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Very cool. The description will be great for conda as well.

**Comment by jpfeuffer** [comment]
I don't see another commit.

**Comment by oliveralka** [comment]
I somehow see the:
[ADD] v3.04, clang-1100.0.33.8, depl. target 10.9       95962f2

(which should already be merged)

**Comment by jpfeuffer** [comment]
ah maybe you branched from master that was not updated yet or something. But as long as git does not show any changes it should be fine.

**Pull request merged**
