### PR TITLE
update to ThermoRawFileParser1.4.4

### PR DESCRIPTION
**Pull request by timosachsenberg**
mainly because of:
- Added support for Thermo Astral

### CODE REVIEW

**Review by jpfeuffer — COMMENTED** [review]
Does this mean we do not have to require mono anymore if they are shipping the dlls now?

**Comment by timosachsenberg** [comment]
I think so but someone would need to test

**Comment by timosachsenberg** [comment]
I asked in the TRFP github

**Comment by timosachsenberg** [comment]
"Hi 
no, mono is still a requirement. The runtime folder only contains the runtime versions of the Mono.Unix package (it is released that way)."

**Pull request merged**
