### PR TITLE
Mavenized - LuXor Snapshot 2.1

### PR DESCRIPTION
**Pull request by oliveralka**
LuciPhor2 / LuXor had some issues with higher java version > 9 
- Mavenized version works with later versions. 

Tested: openjdk 13 2019-09-17

https://github.com/dfermin/lucXor/issues/2
https://github.com/dfermin/lucXor/issues/4

https://github.com/dfermin/lucXor/tree/mavenize

### CODE REVIEW

**Comment by timosachsenberg** [comment]
does this work with our Adapter? If so I would merge

**Comment by oliveralka** [comment]
Was tested using our Adapter (OpenMS 2.4.0, 2.5.0dev - macOS) with installed openjdk 13 2019-09-17. 

Would be happy if someone else can test as well, but should work - the earlier version was only functional to java 9.

**Comment by timosachsenberg** [comment]
ok let's merge. Do we have some test data?

**Comment by oliveralka** [comment]
@timosachsenberg I added a "TOPP_LuciphorAdapter_1" thirdparty test a while ago.

**Pull request merged**
