### PR TITLE
Fix/siriuslibpath

### PR DESCRIPTION
**Pull request by lukaszimmermann**
Fixes the lib path of Sirius in the CLASSPATH for MacOS and Linux

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Looks good. Will merge before the nightlies.

**Comment by jpfeuffer** [comment]
Btw: We could also think about supporting both layouts.

**Comment by lukaszimmermann** [comment]
What do you mean by layout?

**Comment by jpfeuffer** [comment]
The folder structures. One might be just a git clone for developers, the other is a flat folder structure after installation with only the platform specific binaries.

**Pull request merged**
