### PR TITLE
added maracluster executables

### PR DESCRIPTION
**Pull request by Leon-Bichmann**

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Ok the executables work for me. Can you quickly add the version number and a link, to the Version file in the repo here?

**Comment by Leon-Bichmann** [comment]
https://github.com/statisticalbiotechnology/maracluster/releases
release 0.04

**Comment by jpfeuffer** [comment]
You can use github to add this to the  versions file on your branch quickly

**Comment by oliveralka** [comment]
+1

**Pull request merged**
