### PR TITLE
Percolator: Update to v3.02.0 for Linux64 and Windows

### PR DESCRIPTION
**Pull request by lukaszimmermann**
Updates the Percolator executable to 3.02nightly, which contains new experimental options,
such as  `--train-best-positive`.

This is now just the executable for Linux 64. For Mac, I would need a machine to build the
executable there. I will try later for Windows at home.

Addresses: [https://github.com/OpenMS/OpenMS/issues/3628](https://github.com/OpenMS/OpenMS/issues/3628)

### CODE REVIEW

**Comment by timosachsenberg** [comment]
cool. could we use the ones from https://github.com/percolator/percolator/releases ?

**Comment by lukaszimmermann** [comment]
Done

**Comment by lukaszimmermann** [comment]
Percolator Update for Windows 32bit and 64bit added.

**Comment by jpfeuffer** [comment]
Mac is still missing?

**Comment by lukaszimmermann** [comment]
Yes. I cannot perform the update, as I currently do not have access to  a Mac.

**Comment by oliveralka** [comment]
@lukaszimmermann @jpfeuffer 
I am trying to build percolator static on MacOS (for this PR) - but I ran into some issues.

`ld: library not found for -lcrt0.o` 

I use the following build script:
[percolator_build_osx.sh.zip](https://github.com/OpenMS/THIRDPARTY/files/2513840/percolator_build_osx.sh.zip)

**Comment by jpfeuffer** [comment]
I think you cannot link everything static on MacOS. You have to be selective. At least all system libs should be fine to be dynamically linked. https://stackoverflow.com/questions/39278390/static-linking-with-dylib-ld-library-not-found-for-lcrt0-o-collect2-error-ld

**Comment by oliveralka** [comment]
@jpfeuffer Could you shortly test if the MacOS one is working for you? 

It seems that static linking is not necessary for MacOS (thanks @lukaszimmermann).

**Comment by jpfeuffer** [comment]
Yes, Mac works. Rest is tested?
```
./percolator:
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
```
That is perfect, every Mac will have that.

**Pull request merged**
