### PR TITLE
[FIX] sirius script

### PR DESCRIPTION
**Pull request by lukaszimmermann**
realpath did not work with spaces in path
Use absolute path for executables in this script

### CODE REVIEW

**Comment by oliveralka** [comment]
Did work with the current build & this script in KNIME.

**Comment by jpfeuffer** [comment]
Ah nice. You installed the current RC plugin and replaced the script there?

**Comment by oliveralka** [comment]
Yes.

**Comment by jpfeuffer** [comment]
Hm okay but note that the current solution now requires a bash (which is not standard on every linux). To be honest it feels like this whole script is more complex than it would have to be. The question is, which cases we want to cover with this?

**Comment by jpfeuffer** [comment]
But in theory we can merge this for the release and think about it another time. Should work in 99% of the cases.

**Comment by oliveralka** [comment]
Then merge for the release and let's think about it further. The most important is that APP_Home is set correctly. 

The bottom part of the script is from the guys in Jena, so I'm not sure what is really needed for Sirius. In our case we need the Home, Lib (flat & non-flat), Java. 
In case of Sirius you can specify if you want to use GUROBI.

**Comment by jpfeuffer** [comment]
Yes. This is kind of what I mean. Ok I will merge.

**Comment by lukaszimmermann** [comment]
I think that the shell script should be replaced by a Python script to ensure portability.

**Comment by jpfeuffer** [comment]
This PR made the nightlies fail:
https://abibuilder.informatik.uni-tuebingen.de/jenkins/view/OpenMS/job/openms_nightly_packaging/compiler=g++-4.8,os_label=ubuntu_1404/95/testReport/junit/projectroot.src.tests/topp/TOPP_SiriusAdapter_1/

**Pull request merged**
