### PR TITLE
[ADD] Executable and Makefile of SpectraST

### PR DESCRIPTION
**Pull request by lukaszimmermann**
Makefile can be used to build executable on a Linux 64bit machine

The dependencies are also included as tarballs and will be built by the Makefile.
Sources from the ramp parser of TPP were also included.
Not sure whether further License information have to be included.

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Great. Thanks for picking up the task of including a spectral library search engine.
However, I am not sure if we want the sources in this repository. This repository is directly used for packaging of our installers and KNIME executables. Executables are copied and referenced in our wrappers. Maybe it would be best to begin with a separate repository, like hendrik did for Fido.

**Comment by lukaszimmermann** [comment]
Many thanks  for the feedback.

Then I will open a new repository for spectrast and commit only the executable to this one, okay?

**Comment by cbielow** [comment]
Agreeing with Julianus, this is not a good place for source code.
If a separate repo is created, I#d suggest to remove the .svn subdirs as well -- considerable cleanup.

**Comment by jpfeuffer** [comment]
Yes, executables are very welcome here. We put the licensing info in the License.txt in the main repository so it is presented during installation, no matter if you chose to install Thirdparty software or not.

**Pull request closed without merging**
