### PR TITLE
Update comet executable to 2023 version

### PR DESCRIPTION
**Pull request by jonasscheid**
According to #97

### CODE REVIEW

**Comment by timosachsenberg** [comment]
@jpfeuffer Jonas downloaded it from the release page. I think the comet guys build on Ubuntu. Size looks like it could be static.
Could this work?
@jonasscheid If so, we probably should also add the executables for mac and win

**Comment by jonasscheid** [comment]
Actually I cloned the comet repo and built the executable from source. I could also exchange the executable with the ones [comet provides](https://github.com/UWPR/Comet/releases). Let me check if that one works on my ubuntu instance

**Comment by jpfeuffer** [comment]
I am not sure how much of the selfbuilding is needed these days. It should be a standalone executable if possible and built against a low enough Glibc/macOS SDK such that it runs on the same OS versions that we support with the OpenMS tools.
Windows should not be an issue these days, as long as they keep their ABI compatibility in the VS Redistributables.

Which executable platforms can be downloaded @jonasscheid ?

**Comment by timosachsenberg** [comment]
https://github.com/UWPR/Comet/releases/tag/v2023.01.0
but the actions look like they use only -latest systems: e.g.
https://github.com/UWPR/Comet/blob/master/.github/workflows/linux-build.yml

**Comment by jpfeuffer** [comment]
Hmm yes this might be a problem.

**Comment by timosachsenberg** [comment]
what would be alternatives?
- taking the github action from comet and setting the OS to the lowest possible version?
btw I wrote an issue in the comet repo. Maybe they could do that (if it helps).

**Comment by jpfeuffer** [comment]
For Ubuntu that works (although some kind of manylinux is of course preferable). For macOS one should additionally set the MACOS_DEPLOYMENT_TARGET to a low version (maybe 10.15 these days)?

**Comment by jonasscheid** [comment]
Also worked for me on ubuntu 👍

**Comment by jpfeuffer** [comment]
which Ubuntu version do you have?

**Comment by jonasscheid** [comment]
> 
> Recompiled from source on Linux 5.4.0-65-x86_64 with:
> 
>  ldd (Ubuntu GLIBC 2.31-0ubuntu9.7) 2.31
> 
>  g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0`

-> 20.04.1

**Comment by jpfeuffer** [comment]
Okay. 20.04 with glibc 2.31 is fine.

**Comment by poshul** [comment]
If we only need the MacOS version now to proceed (with Windows working, and @jonasscheid's Linux version compatible with 20.04) Is it worth just building the MacOS version on Abibuilder and including that?

**Comment by jpfeuffer** [comment]
Yes, that will work. As expected, I get:
```
dyld: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: /Users/pfeuffer/Downloads/comet.macos.exe (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/pfeuffer/Downloads/comet.macos.exe
[1]    23267 abort      ~/Downloads/comet.macos.exe
```

with the provided version. Since I am on 11.7.3

**Comment by jonasscheid** [comment]
Would this new release of comet fix the problems with your Mac version @jpfeuffer? https://github.com/UWPR/Comet/releases/tag/v2023.01.1

It also fixed a (I would say crucial bug for us as well https://github.com/UWPR/Comet/issues/33)

**Comment by jpfeuffer** [comment]
Macos 11 should be fine. I did not test yet but I am also currently hacking my Mac to make it install a newer OS.

**Comment by cbielow** [comment]
The latest release seems to have major bug (see Comet Mailing list).
Jimmy is usually very fast to fix those and publish a new release, but we should not ship the current version.

**Comment by jonasscheid** [comment]
Another one? Or do you mean this one https://github.com/UWPR/Comet/issues/33

**Comment by jke000** [comment]
> The latest release seems to have major bug (see Comet Mailing list). Jimmy is usually very fast to fix those and publish a new release, but we should not ship the current version.

@cbielow, is the major bug the missing support for mzML/mzXML files that don't have the optional scan indexes?   The Comet google group has been pretty quiet so this must be it but I want to make sure I address all open issues before I make the next release.

**Comment by cbielow** [comment]
> > The latest release seems to have major bug (see Comet Mailing list). Jimmy is usually very fast to fix those and publish a new release, but we should not ship the current version.
> 
> @cbielow, is the major bug the missing support for mzML/mzXML files that don't have the optional scan indexes? The Comet google group has been pretty quiet so this must be it but I want to make sure I address all open issues before I make the next release.

Yes indeed. That was the issue i was referring to.

**Comment by jonasscheid** [comment]
New Comet release is there! I uploaded the executables. There is now a hidden parameter [export_additional_pepxml_scores](https://uwpr.github.io/Comet/parameters/parameters_202301/export_additional_pepxml_scores.html) (for us) to obtain additional features that are already contained in the pin file 🤙🏼 Thanks to @jke000 for the quick release

**Pull request merged**
