### PR TITLE
update Percolator to 304

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Comment by timosachsenberg** [comment]
@jpfeuffer @oliveralka do you recall how we generated the mac binaries? Lukas does not provide one.
And on linux. Can we use one of the releases?

**Comment by timosachsenberg** [comment]
ping

**Comment by jpfeuffer** [comment]
No version.txt or readme to update?

**Comment by jpfeuffer** [comment]
Maybe add one, together with build instructions on macOS.

**Comment by timosachsenberg** [comment]
yep README.MD would be good
and also that we need to update https://github.com/OpenMS/THIRDPARTY/blob/update/percolator304/VERSION
everytime we update thirdparties ;)

**Comment by oliveralka** [comment]
See  #65

**Comment by timosachsenberg** [comment]
Nice

**Pull request merged**
