### PR TITLE
[ADD] Sirius3.5 (linux, osx, win)

### PR DESCRIPTION
**Pull request by oliveralka**
Executables and libraries of Sirius3.5 for the SiriusAdapter

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Hmmm hmmm.. not sure what to do about this. It will be our first GUI app and it requires a lot of redundant Java libraries and startup scripts. We should discuss a bit before merging.

**Comment by oliveralka** [comment]
Updated Pull request. Only one Library for Sirius class files. Library files for glpk for each Os. Different executables for each Os.

**Comment by jpfeuffer** [comment]
Okay great! Only one thing: Can you check if we can get rid of some libraries if we do not use the GUI? Then I would be for a merge.

**Comment by oliveralka** [comment]
This seems to be the minimal possible build, right now.

**Comment by jpfeuffer** [comment]
Ok. If you give me your ok because of our discussion of the filenames, I will merge. Tell me when your thirdparty test passes.

**Comment by oliveralka** [comment]
test passed - should be fine!

**Comment by jpfeuffer** [comment]
Oops I think the automatic merge via svn checkout fails with that structure..

**Comment by jpfeuffer** [comment]
I will look for an alternative

**Comment by jpfeuffer** [comment]
svn export --force works. will update travis

**Comment by oliveralka** [comment]
Should I open a new pull request? What is the Problem?

**Comment by jpfeuffer** [comment]
No fine. Can stay closed here.

**Pull request merged**
