### PR TITLE
[ADD] SpectraST executable from TPP and README

### PR DESCRIPTION
**Pull request by lukaszimmermann**
README contains description of the compilation specifications.

### CODE REVIEW

**Comment by hroest** [comment]
@jpfeuffer @cbielow is there a policy about having executables only for a single platform (e.g. Linux) or is that ok (for now)?

**Comment by cbielow** [comment]
Full coverage would be desirable, but having one is better than none I guess.

**Comment by hroest** [comment]
I agree, my view is lets start with Linux but eventually add the SpectraST executables for the other OS as well - I guess we could use the pre-compiled ones from the TPP distrubution?

**Comment by jpfeuffer** [comment]
Having only one platform is fine for now. We can disable the availability of the node e.g. in KNIME (on these platforms). Or include the node and require that the user finds/builds an executable himself and places it with the others. But yes, let's start with Linux.

**Comment by hroest** [comment]
so lets merge?

**Comment by lukaszimmermann** [comment]
I can test the windows executable on the weekend at home  where I have access to a machine running Windows. For OSX I need to check, maybe I can get a Macbook for testing and building.

**Comment by jpfeuffer** [comment]
Where did you put the sources and the Makefiles now?

**Comment by lukaszimmermann** [comment]
In a separate repository: 
https://github.com/lkszmn/SpectraST

**Comment by timosachsenberg** [comment]
what'S the status here?

**Comment by lukaszimmermann** [comment]
Linux binary should be fine. I am going to prepare the Windows executables. TPP is not officially supported for Mac OSX. Should we  try to include it anyway or omit the executable for this platform?

**Comment by timosachsenberg** [comment]
I think it would be great to have SpectraST on mac

**Comment by lukaszimmermann** [comment]
Ok I am going to try to build the executable on Mac

**Comment by lukaszimmermann** [comment]
Added executables for MacOS 64bit and Win64.

**Comment by jpfeuffer** [comment]
Mac works for me +1 (10.12.whatever)

**Comment by jpfeuffer** [comment]
win binary works too. will merge.

**Pull request merged**
