### PR TITLE
Feature/percolator-noxml

### PR DESCRIPTION
**Pull request by mwalzer**
Let's try percolator w/o xml links as we take care of xml ourselves. Also, smaller binaries. Maybe let's also keep the name of the binaries a bit more descriptive.

### CODE REVIEW

**Comment by mwalzer** [comment]
@jpfeuffer no way for me to check if the mac binaries would still be called the same as the dmg .. can you check?

**Comment by jpfeuffer** [comment]
Hey yes you need to mount the dmg, extract the pkg (installer is broken), then navigate to the binary. Not sure if you can do it on linux.

**Comment by mwalzer** [comment]
Jup, tried, but I'm unsure. The mount found me a file I suspect to contain the binary called _Archive.pax_ ... Does it @jpfeuffer ?

**Comment by jpfeuffer** [comment]
yup

**Comment by jpfeuffer** [comment]
Ah and you should rename the files to a version independent name that matches the default in the adapter (in this case percolator[.exe])

**Comment by jpfeuffer** [comment]
What's the status here?

**Comment by jpfeuffer** [comment]
Please update and remove the linux binary. Was update in #15 already.

**Comment by timosachsenberg** [comment]
already included by lukas PR

**Pull request closed without merging**
