### PR TITLE
changed 32bit tandem to old, working version Sledgehammer

### PR DESCRIPTION
**Pull request by FabianAicheler**
(i.e. latest 32bit)

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Does that mean that there is no 32bit build for the latest version?

**Comment by timosachsenberg** [comment]
seems so

**Comment by jpfeuffer** [comment]
hmm.. will be a pain to test two diverging versions once they produce different results.

**Comment by timosachsenberg** [comment]
I agree. it might be time to think about dropping 32bit support...

**Comment by timosachsenberg** [comment]
I opened this topic for discussion on: https://github.com/OpenMS/OpenMS/issues/2247

**Comment by jpfeuffer** [comment]
Great. But I think to have a working version in here is a good idea. +1 to merge. If we plan to remove 32bit completely, we get rid of the folder later.

**Pull request merged**
